### ISSUE TITLE
Show the names of people/parties added/removed

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/review_changes#3]
Currently we just list the IDs, which isn't the most helpful: 
- https://github.com/everypolitician/everypolitician-data/pull/3458
- https://github.com/everypolitician/everypolitician-data/pull/3474

Would be good to show the name as well (probably good to also keep showing the ID)

**Comment by chrismytton** [comment]
This would probably be a good opportunity to start using [everypolitician-popolo](https://github.com/everypolitician/everypolitician-popolo).
